import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LeftSidebar from "./LeftSidebar";
import RightSidebar from "./RightSidebar";
import { Fragment, ReactNode } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Breadcrumbs } from "./page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "jad choaib",
  description: "Generated by create next app",
};
interface LayoutProps {
  children: ReactNode;
}

const Layout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <>
      <html lang="en">
        <head>
          <link
            href="https://fonts.googleapis.com/css2?family=Azeret+Mono:ital,wght@0,100..900;1,100..900&display=swap"
            rel="stylesheet"
          />
        </head>
        <body>
          <div className="container">
            <div className="left-sidebar">
              <LeftSidebar />
            </div>
            <div className="main-content">
              <Breadcrumbs />
              {children}
            </div>
            <div className="right-sidebar">
              <RightSidebar />
            </div>
          </div>
        </body>
      </html>
    </>
  );
};

export default Layout;
